-- Disable RLS for development
-- This script disables Row Level Security on all tables for easier development

-- Disable RLS on all tables
ALTER TABLE IF EXISTS users DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS user_profiles DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS clients DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS service_orders DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS service_purchases DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS messages DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS notifications DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS countries DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS languages DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS service_categories DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS services DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS consultant_countries DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS consultant_spoken_languages DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS consultant_country_services DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS message_attachments DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS conversation_participants DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS commission_payouts DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS commission_payout_items DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS country_pages DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS country_media DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS country_testimonials DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS country_settings DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS country_configurations DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS country_form_sections DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS country_form_fields DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS country_packages DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS country_services DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS country_config_audit DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS blog_posts DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS faqs DISABLE ROW LEVEL SECURITY;

-- Grant full access to authenticated users
GRANT ALL ON ALL TABLES IN SCHEMA public TO authenticated;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO authenticated;
GRANT ALL ON ALL FUNCTIONS IN SCHEMA public TO authenticated;

-- Grant full access to anon users (for public access)
GRANT ALL ON ALL TABLES IN SCHEMA public TO anon;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO anon;
GRANT ALL ON ALL FUNCTIONS IN SCHEMA public TO anon;

-- Grant full access to service_role
GRANT ALL ON ALL TABLES IN SCHEMA public TO service_role;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO service_role;
GRANT ALL ON ALL FUNCTIONS IN SCHEMA public TO service_role;