# Ana Consulting19 Deployment - Tüm uygulamalar tek URL'de
[build]
  publish = "apps/marketing/dist"
  command = "npm run build:all"

[build.environment]
  NODE_VERSION = "18"

# SPA yönlendirmesi - tüm route'lar marketing app'e gider
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Cache ayarları
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "max-age=31536000"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "max-age=31536000"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "max-age=31536000"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"